### ISSUE TITLE
License confirmation?

### ISSUE THREAD

**Issue by pombredanne** [ghiscoding/excel-builder.js#2]
I see that the license is declared as ` "(MIT OR GPLv3)"` but the original from @stephenliberty at https://github.com/stephenliberty/excel-builder.js was under GPL v3 and had some code under MIT, making it "GPL AND MIT" but not a "GPL or MIT" choice?
I see this was introduced by https://github.com/ghiscoding/excel-builder.js/commit/7b92d441f39c6bca42f8b9aab23af202b00c8457

What was the rationale for the license change? was @stephenliberty involved and gave its OK?

Thank you for your answer!

**Comment by ghiscoding** [comment]
he really has both in his [License](https://github.com/stephenliberty/excel-builder.js/tree/master/License) folder so that's the rational

EDIT
I remember seeing something somewhere from the author that he had dual license, and here it is

**Note**
his website is no longer available but we can use the webtime archive to see it at this link, then scroll to the bottom of the page and you will see the licenses
https://web.archive.org/web/20160907051738/http://excelbuilderjs.com/index.html

![image](https://user-images.githubusercontent.com/643976/166153660-240497dc-4091-4abf-b09b-85964ce9fdf6.png)

**Comment by pombredanne** [comment]
@ghiscoding Thanks for the quick reply!

> he really has both in his License folder https://github.com/stephenliberty/excel-builder.js/tree/master/License so that's the rationale

I saw this too, but I think that the copyright in https://github.com/stephenliberty/excel-builder.js/blob/master/License/MIT.txt is from @Stuk "Copyright (c) 2009 Stuart Knightley" and jszip which is bundled in the compiled version and is under an MIT license.... and it seems highly unlikely (to me) that @Stuk MIT applies otherwise as a choice of license for the overall package?

**Comment by ghiscoding** [comment]
I follow more what the author of lib wrote on his own website (only available from the web archive) and I think the way I have it displayed is valid for that reason. I can add it to the readme if that's any helpful but I'm not planning to change the description of the license since I am following what the author wrote

**Comment by pombredanne** [comment]
> I follow more what the author of lib wrote on his own website (only available from the web archive) and I think the way I have it displayed is valid for that reason. I can add it to the readme if that's any helpful but I'm not planning to change the description of the license since I am following what the author wrote


oh, I did not knew there was a statement from upstream! do you have a URL?

**Comment by pombredanne** [comment]
just saw your above ...let me check

**Comment by pombredanne** [comment]
ok, this looks good:

> License
> Dual - MIT and GPLv3. Use whatever is appropriate in your project.

means clearly (even though it says "and") that this is a choice of `MIT OR GPLv3.`

I think you should clarify this in the readme as this is rather ambiguous otherwise :)

**Comment by pombredanne** [comment]
@ghiscoding Thank you ++ for doing the research!
So you did not relicense anything, but just clarified the licensing documentation along the lines of @stephenliberty  statements! :+1:

**Comment by stephenliberty** [comment]
Hi - 

Short version - the GPLv3 / MIT dual is compatible with libraries that are MIT licensed. Read in on https://www.gnu.org/licenses/license-list.html#GPLCompatibleLicenses (search for MIT, it's described under the Expat License section). In the case of the packed MIT license, the name was a copy/pasta error (whoops, ten years ago now?) from the jszip library. `@Stuk` doesn't have anything to do with that project beyond providing a library for it. 

The project was dual licensed because, at the time, there was a lot of hubub about what license type to use. I settled on dual licensing because I wanted to allow strong GPLv3 projects (ones that rejected MIT/X11/etc.. I can't remember why they did that..) to be able to use this. 

Honestly, I'm beyond surprised that this little library is still being used today, but feel free to fix that license file/README/whatever with the appropriate names.

**Comment by pombredanne** [comment]
@stephenliberty thank you ++ for the confirmation!

> Honestly, I'm beyond surprised that this little library is still being used today, but feel free to fix that license file/README/whatever with the appropriate names.

good code dies hard :bow:

**Comment by ghiscoding** [comment]
@stephenliberty wow a confirmation from the author itself, how cool is that? 😃 For a long time I wanted to thank you for all of the hard work that you have done in creating this library, I thought that you had left GitHub scene but I'm happy to be able to thank you today after all these years. Indeed your library was the best at the time and is still quite useful and used by many.

> Honestly, I'm beyond surprised that this little library is still being used today, but feel free to fix that license file/README/whatever with the appropriate names.

Since I have your blessing, I will replace in the coming days to the MIT license which is a more permissive license to use. 
Thanks for all of what you've done, if you have a link for donation, I can also add it to the readme and I'll do a donation myself. 🤝

**Comment by pombredanne** [comment]
@ghiscoding I am psyched and in awe that by bugging you on a mundane license issue we have such a great outcome and so quickly :bow: ... you both rock!

**Comment by stephenliberty** [comment]
Yeah - I think just dropping the GPLv3 portion is the right way to go. Legally, it's a a LOT easier to do that than to change to a different license or anything because  you don't need to contact every other author that has ever touched anything in the codebase. And I am still around, just not working on this. The small story is that I was just getting a lot of emails from people asking for help, some nasty ones about "why did you do this when you could have done that", bots trying to break into my account, etc. It was just a lot of work to try and keep everything going and improve upon, while at the same time I was dealing with depression and other personal issues. 

There are parts of me that would really enjoy picking this back up, but I've stopped programming as a 'hobby' - three kids and a farm will do that to you. Gotta have enough time in the day to pet your turkeys and geese, ya know? Hah. Glad this work has helped ya'll - feel confident in making changes as you see fit. Especially tests. Oh my word did this thing need proper tests.

Anyway, no donation - if you've got family or a good friend, just give one of them a call and see how they're doing. It's silly, but in this world it sorta feels like that's the most valuable currency of all - your time.

**Comment by ghiscoding** [comment]
Alright I made the following changes
- delete previous GPLv3 License from the project
- replace Stuart's name with Stephen's name
- renamed the `License/MIT.txt` to [LICENSE.md](https://github.com/ghiscoding/excel-builder.js/blob/master/LICENSE.md) and moved it to the root of the project.

You can double-check the new [LICENSE.md](https://github.com/ghiscoding/excel-builder.js/blob/master/LICENSE.md) file and a new version `v2.1.7` of [excel-builder-webpacker](https://www.npmjs.com/package/excel-builder-webpacker) was released with the new license. 

Thanks everyone for chiming in, feel free to write back if there's problems in any of the changes. 
Cheers
